const $ = (id) => document.getElementById(id);
const ISSUE_LABELS = {did_not_answer:"没有回答问题",fact_error:"事实错误",subject_error:"人物 / 主体错误",logic_error:"句内逻辑错误",unsupported_claim:"无依据扩写",unknown_handling:"不知道时处理不当",persona_drift:"人格退化",other:"其他"};
let report = null;
let review = {reviews:{},completed:0,total:0,good:0,bad:0};

async function request(path,method="GET",body=null){const options={method,headers:{}};if(body!==null){options.headers["Content-Type"]="application/json";options.body=JSON.stringify(body);}const response=await fetch(path,options);const value=await response.json();if(!response.ok)throw new Error(value.detail||"请求失败");return value;}
function renderProgress(){const done=review.completed||0,total=review.total||0;$("progressBar").style.width=`${total?done/total*100:0}%`;$("progressText").textContent=`${done} / ${total}`;$("breakdown").textContent=done?`好 ${review.good} 条 · 差 ${review.bad} 条`:"尚未开始";}
function issueOptions(saved){const box=document.createElement("div");box.className="issue-options";Object.entries(ISSUE_LABELS).forEach(([value,text])=>{const label=document.createElement("label"),input=document.createElement("input"),span=document.createElement("span");input.type="checkbox";input.value=value;input.checked=saved?.issues?.includes(value)||false;span.textContent=text;label.append(input,span);box.append(label);});return box;}
function renderCases(){const list=$("turnList");list.replaceChildren();$("resultCount").textContent=`${report.cases.length} / ${report.cases.length} 轮`;report.cases.forEach(item=>{const saved=review.reviews[String(item.ordinal)],fragment=$("caseTemplate").content.cloneNode(true),article=fragment.querySelector(".audit-turn");fragment.querySelector(".turn-number").textContent=`第 ${item.ordinal} 轮`;fragment.querySelector(".phase-badge").textContent=item.category;const state=fragment.querySelector(".turn-state");state.textContent=saved?(saved.quality==="good"?"已判好":"已判差"):"未审核";if(saved)state.classList.add(saved.quality);fragment.querySelector(".question").textContent=item.question;fragment.querySelector(".memory").textContent=item.visible_memory;fragment.querySelector(".focus").textContent=item.review_focus;fragment.querySelector("blockquote").textContent=item.answer.response;fragment.querySelector(".latency").textContent=`完整回复 ${(item.answer.elapsed_ms/1000).toFixed(2)} 秒`;fragment.querySelector(".raw-input").textContent=JSON.stringify(item.messages,null,2);const radios=fragment.querySelectorAll('input[type="radio"]');radios.forEach(r=>{r.name=`q-${item.ordinal}`;r.checked=saved?.quality===r.value;});fragment.querySelector(".issue-options").replaceWith(issueOptions(saved));fragment.querySelector("textarea").value=saved?.note||"";fragment.querySelector('input[value="good"]').addEventListener("change",()=>fragment.querySelectorAll('.issue-options input').forEach(i=>i.checked=false));fragment.querySelector(".save-button").addEventListener("click",async()=>{const feedback=article.querySelector(".save-feedback"),quality=article.querySelector('input[type="radio"]:checked')?.value,issues=[...article.querySelectorAll('.issue-options input:checked')].map(i=>i.value),note=article.querySelector("textarea").value;if(!quality){feedback.textContent="请先选择好或差";feedback.className="save-feedback error";return;}feedback.textContent="正在保存...";try{review=await request(`/api/user-review/${item.ordinal}`,"PUT",{quality,issues,note});renderProgress();renderCases();}catch(error){feedback.textContent=error.message;feedback.className="save-feedback error";}});list.append(fragment);});}
async function initialize(){try{[report,review]=await Promise.all([request("/api/review"),request("/api/user-review")]);const controls=report.controls,adapter=controls.adapter_loaded?"Adapter 已加载":"无 Adapter",thinking=controls.thinking?"开启思考":"关闭思考",temperature=Number(controls.temperature??0);$("modelName").textContent=report.model;$("experimentSummary").textContent=`${adapter}、${thinking}、温度 ${temperature}；每轮回复进入后续历史`;$("controlSummary").textContent=`最近 ${controls.history_limit_messages} 条历史 · ${adapter} · ${thinking} · 温度 ${temperature}`;$("speedSummary").textContent=`平均完整回复 ${(report.speed.mean_complete_response_ms/1000).toFixed(2)} 秒`;renderProgress();renderCases();}catch(error){$("reviewError").hidden=false;$("reviewError").textContent=error.message;}}
$("resetReview").addEventListener("click",async()=>{if(!confirm("确定清空全部人工审核吗？"))return;review=await request("/api/user-review","DELETE");renderProgress();renderCases();});initialize();
