const $ = (id) => document.getElementById(id);
const ISSUE_LABELS = {did_not_answer:"没有回答问题",fact_error:"事实错误",subject_error:"人物 / 主体错误",logic_error:"句内逻辑错误",unsupported_claim:"无依据扩写",unknown_handling:"不知道时处理不当",persona_drift:"人格退化",other:"其他"};
let report = null;
let review = {reviews:{},completed_arms:0,total_arms:40,good:0,bad:0};

async function request(path, method="GET", body=null) { const options={method,headers:{}}; if(body!==null){options.headers["Content-Type"]="application/json";options.body=JSON.stringify(body);} const response=await fetch(path,options); const value=await response.json(); if(!response.ok) throw new Error(value.detail||"请求失败"); return value; }
function renderProgress(){const done=review.completed_arms||0,total=review.total_arms||40;$("progressBar").style.width=`${done/total*100}%`;$("progressText").textContent=`${done} / ${total}`;$("breakdown").textContent=done?`好 ${review.good} 条 · 差 ${review.bad} 条`:"尚未开始";}
function issueOptions(ordinal,arm,saved){const box=document.createElement("div");box.className="issue-options";Object.entries(ISSUE_LABELS).forEach(([value,text])=>{const label=document.createElement("label"),input=document.createElement("input"),span=document.createElement("span");input.type="checkbox";input.value=value;input.checked=saved?.issues?.includes(value)||false;span.textContent=text;label.append(input,span);box.append(label);});return box;}
function armPanel(item,arm,label){const saved=review.reviews[String(item.ordinal)]?.[arm];const section=document.createElement("section");section.className="arm";section.innerHTML=`<header><strong>${label}</strong><span>${(item.answers[arm].elapsed_ms/1000).toFixed(2)} 秒</span></header><blockquote></blockquote><section class="manual-review"><div class="review-choice"><strong>单独判断这一侧</strong><label><input type="radio" value="good"><span>好</span></label><label><input type="radio" value="bad"><span>差</span></label></div><fieldset class="issue-fieldset"><legend>问题类型</legend><div class="issue-options"></div></fieldset><label class="note-field"><span>备注</span><textarea maxlength="1000"></textarea></label><div class="save-row"><span class="save-feedback"></span><button class="save-button">保存这一侧</button></div></section>`;section.querySelector("blockquote").textContent=item.answers[arm].response;const radios=section.querySelectorAll('input[type="radio"]');radios.forEach(r=>{r.name=`q-${item.ordinal}-${arm}`;r.checked=saved?.quality===r.value;});section.querySelector(".issue-options").replaceWith(issueOptions(item.ordinal,arm,saved));section.querySelector("textarea").value=saved?.note||"";section.querySelector('input[value="good"]').addEventListener("change",()=>section.querySelectorAll('.issue-options input').forEach(i=>i.checked=false));section.querySelector("button").addEventListener("click",async()=>{const feedback=section.querySelector(".save-feedback"),quality=section.querySelector('input[type="radio"]:checked')?.value,issues=[...section.querySelectorAll('.issue-options input:checked')].map(i=>i.value),note=section.querySelector("textarea").value;if(!quality){feedback.textContent="请先选择好或差";feedback.className="save-feedback error";return;}feedback.textContent="正在保存...";try{review=await request(`/api/user-review/${item.ordinal}/${arm}`,"PUT",{quality,issues,note});renderProgress();renderCases();}catch(error){feedback.textContent=error.message;feedback.className="save-feedback error";}});return section;}
function matches(item){const q=$("searchInput").value.trim().toLowerCase();const cat=$("categoryFilter").value;if(cat!=="all"&&item.category!==cat)return false;const text=[item.question,item.visible_memory,item.review_focus,item.answers.base.response,item.answers.preference.response].join(" ").toLowerCase();return !q||text.includes(q);}
function renderCases(){const items=report.cases.filter(matches),list=$("turnList");list.replaceChildren();$("resultCount").textContent=`${items.length} / ${report.cases.length} 题`;items.forEach(item=>{const fragment=$("caseTemplate").content.cloneNode(true);fragment.querySelector(".turn-number").textContent=`第 ${item.ordinal} 题`;fragment.querySelector(".phase-badge").textContent=item.category;fragment.querySelector(".condition").textContent=item.condition;fragment.querySelector(".question").textContent=item.question;fragment.querySelector(".memory").textContent=item.visible_memory;fragment.querySelector(".focus").textContent=item.review_focus;fragment.querySelector(".raw-input").textContent=JSON.stringify(item.messages_by_arm||item.messages,null,2);const grid=fragment.querySelector(".pair-grid");grid.append(armPanel(item,"base",report.arms?.base||"A 裸基座 + Prompt/记忆"),armPanel(item,"preference",report.arms?.preference||"B 偏好 Adapter"));list.append(fragment);});}
async function initialize(){try{[report,review]=await Promise.all([request("/api/review"),request("/api/user-review")]);$("armSummary").textContent=`${report.arms.base} · ${report.arms.preference}`;const counts=new Map();report.cases.forEach(item=>counts.set(item.category,(counts.get(item.category)||0)+1));$("caseSummary").textContent=`${report.cases.length} 条封存测试 · ${[...counts].map(([name,count])=>`${name} ${count}`).join(" · ")}`;const filter=$("categoryFilter");[...counts.keys()].forEach(category=>{const option=document.createElement("option");option.value=category;option.textContent=category;filter.append(option);});renderProgress();renderCases();}catch(error){$("reviewError").hidden=false;$("reviewError").textContent=error.message;}}
$("searchInput").addEventListener("input",renderCases);$("categoryFilter").addEventListener("change",renderCases);$("resetFilters").addEventListener("click",()=>{$("searchInput").value="";$("categoryFilter").value="all";renderCases();});$("resetReview").addEventListener("click",async()=>{if(!confirm("确定清空全部人工审核吗？"))return;review=await request("/api/user-review","DELETE");renderProgress();renderCases();});initialize();
